// BLOOM Heartbeat Engine - Human Escalation
// Handles handoffs to humans with proper analysis and recommendations

import { createLogger } from '../logging/logger.js';
import { ghlClient } from '../integrations/ghl.js';
import { emailClient } from '../integrations/email.js';

const logger = createLogger('escalate');

export async function escalate(decision, agentConfig) {
  logger.info(`🚨 Escalating to human: ${decision.issue}`, {
    urgency: decision.urgency,
    confidence: decision.confidence
  });

  try {
    // Format the escalation message
    const escalationMessage = formatEscalationMessage(decision, agentConfig);

    // Send notification to human contact
    await notifyHuman(escalationMessage, agentConfig, decision.urgency);

    // Create tracking task in GHL
    const trackingTask = await createEscalationTask(decision, agentConfig);

    logger.info('✅ Escalation completed', {
      issue: decision.issue,
      urgency: decision.urgency,
      taskId: trackingTask.id
    });

    return {
      success: true,
      escalationId: trackingTask.id,
      notificationSent: true,
      urgency: decision.urgency
    };

  } catch (error) {
    logger.error('❌ Escalation failed:', { message: error.message, stack: error.stack }, {
      issue: decision.issue
    });

    // Fallback: try to create at least a task
    try {
      await ghlClient.createTask({
        title: `URGENT: Escalation Failed - ${decision.issue}`,
        body: `Automated escalation failed with error: ${error.message}\n\nOriginal issue: ${decision.issue}`,
        assignedTo: agentConfig.humanContact?.ghlUserId || 'admin',
        priority: 'HIGH',
        completed: false
      });
    } catch (fallbackError) {
      logger.error('Fallback escalation task creation failed:', { message: fallbackError.message });
    }

    return {
      success: false,
      error: error.message,
      escalationId: null
    };
  }
}

function formatEscalationMessage(decision, agentConfig) {
  const timestamp = new Date().toLocaleString('en-US', {
    timeZone: 'America/New_York',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit'
  });

  return `🤖 AGENT ESCALATION - ${decision.urgency} PRIORITY

**Agent**: ${agentConfig.name} (${agentConfig.role})
**Client**: ${agentConfig.client}
**Time**: ${timestamp} EST
**Confidence**: ${Math.round((decision.confidence || 0) * 100)}%

## ISSUE SUMMARY
${decision.issue}

## MY ANALYSIS
${decision.analysis || 'No detailed analysis provided'}

## WHAT I'VE ALREADY CHECKED
${formatAnalysisPath(decision.analysis_path)}

## HYPOTHESES I'VE TESTED
${formatHypotheses(decision.hypotheses_tested)}

## MY RECOMMENDATION
${decision.recommendation || 'Manual review recommended'}

## CONTEXT & DATA
${formatContextData(decision)}

## NEXT STEPS NEEDED
- [ ] Human review of the situation
- [ ] Decision on recommended action
- [ ] Update agent if new protocols needed
- [ ] Mark this escalation as resolved when complete

---
*This message was generated by ${agentConfig.name} during autonomous operations. Reply to this email or update the corresponding task in GoHighLevel to provide feedback.*

**Agent ID**: ${agentConfig.agentId}
**Escalation ID**: Will be provided after task creation`;
}

function formatAnalysisPath(analysisPath) {
  if (!analysisPath) return 'No specific analysis path recorded';

  if (typeof analysisPath === 'string') {
    return analysisPath;
  }

  if (Array.isArray(analysisPath)) {
    return analysisPath.map((step, index) => `${index + 1}. ${step}`).join('\n');
  }

  return JSON.stringify(analysisPath, null, 2);
}

function formatHypotheses(hypotheses) {
  if (!hypotheses) return 'No hypotheses tested';

  if (Array.isArray(hypotheses)) {
    return hypotheses.map((hypothesis, index) => `${index + 1}. ${hypothesis}`).join('\n');
  }

  if (typeof hypotheses === 'object') {
    return Object.entries(hypotheses)
      .map(([hypothesis, result]) => `• ${hypothesis}: ${result}`)
      .join('\n');
  }

  return JSON.stringify(hypotheses, null, 2);
}

function formatContextData(decision) {
  const context = [];

  if (decision.originalAction) {
    context.push(`**Original Action Attempted**: ${decision.originalAction.action_type}`);
    context.push(`**Action Description**: ${decision.originalAction.description}`);
  }

  if (decision.error) {
    context.push(`**Error Message**: ${decision.error}`);
  }

  if (decision.environmentData) {
    context.push(`**Environment Data**: ${JSON.stringify(decision.environmentData, null, 2)}`);
  }

  return context.length > 0 ? context.join('\n') : 'No additional context data';
}

async function notifyHuman(message, agentConfig, urgency) {
  const humanContact = agentConfig.humanContact;

  if (!humanContact) {
    throw new Error('No human contact configured for escalations');
  }

  const subject = `${urgency} Agent Escalation: ${agentConfig.name}`;

  // Determine notification method
  if (humanContact.method === 'email' && humanContact.address) {
    await sendEmailNotification(humanContact.address, subject, message);
  }

  // Also send SMS if urgency is HIGH or CRITICAL and phone is available
  if ((urgency === 'HIGH' || urgency === 'CRITICAL') && humanContact.phone) {
    const smsMessage = `AGENT ESCALATION (${urgency}): ${agentConfig.name} needs attention. Check email for details.`;
    await sendSMSNotification(humanContact.phone, smsMessage, agentConfig);
  }

  // Always create a GHL notification task
  if (humanContact.ghlUserId) {
    await createGHLNotification(humanContact.ghlUserId, subject, message, urgency, agentConfig);
  }
}

async function sendEmailNotification(emailAddress, subject, message) {
  try {
    await emailClient.sendEmail({
      to: emailAddress,
      from: process.env.AGENT_EMAIL || 'agents@bloomiestaffing.com',
      subject,
      body: message,
      fromName: process.env.AGENT_NAME || 'BLOOM Agent'
    });

    logger.info('📧 Email escalation sent', { to: emailAddress });
  } catch (error) {
    logger.error('Failed to send email notification:', error);
    throw error;
  }
}

async function sendSMSNotification(phone, message, agentConfig) {
  try {
    // Use GHL SMS if available
    await ghlClient.sendSMS({
      phone,
      message,
      fromName: agentConfig.name
    });

    logger.info('📱 SMS escalation sent', { phone });
  } catch (error) {
    logger.warn('Failed to send SMS notification:', error);
    // Don't throw - email should be primary notification method
  }
}

async function createGHLNotification(userId, subject, message, urgency, agentConfig) {
  try {
    const task = await ghlClient.createTask({
      title: subject,
      body: message,
      assignedTo: userId,
      priority: urgency,
      completed: false,
      tags: ['agent_escalation', agentConfig.agentId, urgency.toLowerCase()]
    });

    logger.info('📋 GHL notification task created', { taskId: task.id });
    return task;
  } catch (error) {
    logger.error('Failed to create GHL notification:', error);
    throw error;
  }
}

async function createEscalationTask(decision, agentConfig) {
  const taskTitle = `Agent Escalation: ${decision.issue.substring(0, 50)}${decision.issue.length > 50 ? '...' : ''}`;

  const taskBody = `AGENT ESCALATION DETAILS

Issue: ${decision.issue}
Agent: ${agentConfig.name}
Urgency: ${decision.urgency}
Confidence: ${Math.round((decision.confidence || 0) * 100)}%

Analysis:
${decision.analysis || 'No analysis provided'}

Recommendation:
${decision.recommendation || 'Manual review needed'}

Status: PENDING_HUMAN_REVIEW
Created: ${new Date().toISOString()}

---
To resolve this escalation:
1. Review the issue and analysis above
2. Take appropriate action
3. Update this task with your resolution
4. Mark task as complete
5. Consider if agent protocols need updates`;

  try {
    const task = await ghlClient.createTask({
      title: taskTitle,
      body: taskBody,
      assignedTo: agentConfig.humanContact?.ghlUserId || 'admin',
      priority: decision.urgency || 'MEDIUM',
      completed: false,
      tags: ['agent_escalation', agentConfig.agentId, decision.urgency?.toLowerCase()]
    });

    logger.info('📋 Escalation tracking task created', {
      taskId: task.id,
      urgency: decision.urgency
    });

    return task;
  } catch (error) {
    logger.error('Failed to create escalation task:', { message: error.message, stack: error.stack });
    throw error;
  }
}

// Function to check for resolved escalations
export async function checkResolvedEscalations(agentConfig) {
  try {
    const resolvedTasks = await ghlClient.getTasks({
      assignedTo: agentConfig.humanContact?.ghlUserId,
      tags: ['agent_escalation', agentConfig.agentId],
      status: 'completed',
      updatedSince: new Date(Date.now() - 24 * 60 * 60 * 1000) // last 24 hours
    });

    for (const task of resolvedTasks) {
      // Extract human feedback from task completion
      const feedback = extractFeedbackFromTask(task);
      if (feedback) {
        logger.info('📝 Human feedback received on escalation', {
          taskId: task.id,
          feedback: feedback.summary
        });

        // Store feedback for agent learning
        await storeFeedback(feedback, agentConfig);
      }
    }

    return resolvedTasks.length;
  } catch (error) {
    logger.error('Failed to check resolved escalations:', error);
    return 0;
  }
}

function extractFeedbackFromTask(task) {
  if (!task.completionNotes) return null;

  return {
    taskId: task.id,
    escalationId: task.id,
    resolution: task.completionNotes,
    resolvedAt: task.completedAt,
    feedback: {
      summary: task.completionNotes.substring(0, 200),
      fullResponse: task.completionNotes
    }
  };
}

async function storeFeedback(feedback, agentConfig) {
  // Store feedback in memory system for agent learning
  try {
    const { lettaClient } = await import('../memory/letta-client.js');

    await lettaClient.storeMemory({
      agentId: agentConfig.agentId,
      type: 'human_feedback',
      content: {
        escalationId: feedback.escalationId,
        resolution: feedback.resolution,
        resolvedAt: feedback.resolvedAt,
        feedback: feedback.feedback
      },
      relevanceScore: 0.9
    });

    logger.info('💾 Human feedback stored in agent memory', {
      escalationId: feedback.escalationId
    });
  } catch (error) {
    logger.error('Failed to store feedback in memory:', error);
  }
}