from pathlib import Path

ROOT = Path("/Users/kimberlyflowersmini2/Documents/Codex/2026-07-02/autonomous-sarah-live-current")
OUT_DIR = ROOT / "output" / "master-blog"
OUT_DIR.mkdir(parents=True, exist_ok=True)
OUT = OUT_DIR / "bloomie-perfect-master-blog.html"

html = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Doing Your Own Marketing: The Weekly Rhythm Advisors Actually Need | Bloomie Staffing</title>
  <meta name="description" content="A field-note playbook for advisors doing their own marketing, with a weekly rhythm for pipeline, content, referrals, follow-up, and review.">
  <link rel="canonical" href="https://bloomiestaffing.com/p/blog-master-example-doing-your-own-marketing">
  <script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"What should financial advisors do each week to market consistently?","acceptedAnswer":{"@type":"Answer","text":"Financial advisors should run a five-part weekly rhythm: Monday pipeline review, Tuesday one client-question article or email, Wednesday specific referral follow-up, Thursday nurture or event follow-up, and Friday measurement. This protects advisor time, which Kitces research found was $2,600 of the average $3,119 client acquisition cost."}},{"@type":"Question","name":"Can an AI employee help advisors with marketing without replacing relationship work?","acceptedAnswer":{"@type":"Answer","text":"Yes. A Bloomie can own repeatable marketing operations such as source research, content drafts, referral reminders, CRM cleanup, event follow-up, and Friday reporting while the advisor approves messaging and keeps the client relationship."}},{"@type":"Question","name":"Where should an advisor start if marketing feels scattered?","acceptedAnswer":{"@type":"Answer","text":"Start with warm relationships and source tracking. Fidelity notes existing-client referrals are a major source of qualified leads, and Broadridge-related reporting shows referrals and word of mouth remain a top advisor marketing channel."}}]}</script>
  <style>
    :root{--primary:#F4A261;--accent:#E76F8B;--dark:#2D3436;--ink:#243033;--muted:#5d6a6d;--light:#F8F7F5;--soft:#FFF7EF;--highlight:#FFF3E6;--line:#E5E7EB;--white:#fff}
    *{box-sizing:border-box}body{margin:0;font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:var(--white);color:var(--ink);font-size:16px;line-height:1.7}
    .bloomie-master-nav{position:sticky;top:0;z-index:100;width:100%;background:rgba(255,255,255,.94);backdrop-filter:blur(14px);border-bottom:1px solid rgba(45,52,54,.08)}
    .nav-inner{max-width:1180px;margin:0 auto;padding:1rem 1.5rem;display:flex;align-items:center;justify-content:space-between;gap:1rem}.logo{font-size:1.18rem;font-weight:900;color:var(--dark);text-decoration:none;white-space:nowrap}.logo span{color:var(--primary)}
    .nav-links{display:flex;align-items:center;gap:1.25rem;margin:0;padding:0;list-style:none}.nav-links li{margin:0;padding:0}.nav-links li::before{display:none!important;content:none!important}.nav-links a{color:var(--dark);text-decoration:none;font-size:.9rem;font-weight:800;line-height:1;white-space:nowrap}
    .cta-button{display:inline-flex;align-items:center;justify-content:center;padding:12px 16px;border-radius:10px;background:linear-gradient(135deg,var(--primary),var(--accent));color:#fff!important;box-shadow:0 8px 22px rgba(231,111,139,.22)}
    .blog-back-link{display:inline-flex;align-items:center;gap:.35rem;max-width:1180px;margin:.95rem auto;padding:0 1.5rem;color:rgba(45,52,54,.68);font-size:.9rem;font-weight:750;text-decoration:none}
    .blog-master-header{background:linear-gradient(135deg,var(--primary),var(--accent));color:#fff;text-align:center;padding:72px 24px 64px}.blog-master-header h1{max-width:960px;margin:0 auto;font-size:clamp(2.55rem,4.4vw,3.55rem);line-height:1.05;font-weight:900;letter-spacing:0}.blog-master-header p{max-width:780px;margin:1rem auto 0;font-size:clamp(1.02rem,1.6vw,1.16rem);line-height:1.7;color:rgba(255,255,255,.92)}
    .note-dot{position:relative;display:inline-flex;align-items:center;justify-content:center;width:22px;height:22px;margin-left:8px;border:1px solid rgba(45,52,54,.16);border-radius:50%;background:#fff;color:var(--accent);font-size:.78rem;font-weight:950;line-height:1;vertical-align:middle;box-shadow:0 6px 14px rgba(45,52,54,.12);cursor:help}.note-dot::after{content:attr(data-note);position:absolute;left:50%;bottom:calc(100% + 10px);width:min(280px,80vw);padding:12px 14px;border-radius:12px;background:var(--dark);color:#fff;font-size:.82rem;font-weight:700;line-height:1.45;text-align:left;box-shadow:0 14px 32px rgba(45,52,54,.24);opacity:0;pointer-events:none;transform:translate(-50%,6px);transition:opacity .18s ease,transform .18s ease;z-index:200}.note-dot::before{content:"";position:absolute;left:50%;bottom:calc(100% + 4px);border:6px solid transparent;border-top-color:var(--dark);opacity:0;transform:translateX(-50%);transition:opacity .18s ease;z-index:201}.note-dot:hover::after,.note-dot:focus-visible::after,.note-dot:hover::before,.note-dot:focus-visible::before{opacity:1;transform:translate(-50%,0)}.note-dot:hover::before,.note-dot:focus-visible::before{transform:translateX(-50%)}.blog-master-header .note-dot{margin-left:10px;transform:translateY(-8px)}
    .hero-image{width:100%;max-width:980px;aspect-ratio:16/9;object-fit:cover;display:block;margin:-28px auto 0;border-radius:18px;box-shadow:0 22px 55px rgba(45,52,54,.24);border:1px solid rgba(255,255,255,.7);position:relative;z-index:2}
    .podcast-player{max-width:980px;margin:22px auto 0;padding:22px;border:1px solid rgba(45,52,54,.12);border-radius:16px;background:var(--soft);box-shadow:0 12px 28px rgba(45,52,54,.08);position:relative;z-index:2}.podcast-top{display:flex;align-items:flex-start;justify-content:space-between;gap:18px;flex-wrap:wrap;margin-bottom:14px}.podcast-label{margin:0 0 5px;color:var(--accent);font-weight:900;font-size:.78rem;letter-spacing:.08em;text-transform:uppercase}.podcast-player h2{margin:0 0 8px;padding:0;border:0;color:var(--dark);font-size:1.28rem;line-height:1.25}.podcast-player p{margin:0;color:#465154;font-size:.98rem;line-height:1.55}.podcast-status{font-size:.9rem;color:var(--muted);font-weight:800;white-space:nowrap}.audio-placeholder{margin-top:12px;padding:14px 16px;border-radius:12px;background:#fff;border:1px solid var(--line);color:var(--muted);font-weight:800}
    .content{max-width:820px;margin:0 auto;padding:54px 24px}.author-row{display:flex;align-items:center;gap:14px;margin-bottom:28px;color:var(--muted);font-size:.95rem}.author-avatar-ring{width:66px;height:66px;border-radius:50%;background:linear-gradient(135deg,var(--primary),var(--accent));padding:4px;flex:0 0 auto}.author-row img{width:58px;height:58px;border-radius:50%;object-fit:cover;border:3px solid #fff}.author-name{font-weight:900;color:var(--dark)}
    blockquote{margin:0 0 36px;padding:24px 26px;border-left:6px solid var(--primary);background:var(--soft);color:#384548;font-size:1.2rem;font-style:italic;border-radius:0 12px 12px 0}h2{margin:42px 0 14px;padding-top:18px;border-top:4px solid var(--accent);color:var(--dark);font-size:1.75rem;line-height:1.2}p{margin:0 0 18px}.highlight{margin:24px 0;padding:20px 22px;border-left:5px solid var(--primary);background:var(--highlight);border-radius:0 12px 12px 0}.highlight strong{display:block;color:var(--dark);margin-bottom:6px}ul{padding-left:0;margin:20px 0;list-style:none}li{position:relative;margin:0 0 12px;padding-left:24px}li::before{content:">";position:absolute;left:0;color:var(--accent);font-weight:900}
    .stat-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin:24px 0}.stat-card{background:#fff;border:1px solid var(--line);border-radius:14px;padding:18px;box-shadow:0 10px 24px rgba(45,52,54,.06)}.stat-number{display:block;color:var(--accent);font-size:1.75rem;line-height:1;font-weight:950;margin-bottom:8px}.stat-card p{margin:0;color:#485457;font-size:.94rem;line-height:1.5}a.source-link{color:#b44a65;font-weight:800;text-decoration:underline;text-decoration-thickness:1px;text-underline-offset:3px}
    .faq-accordion{margin:44px 0 18px}.faq-accordion h2{margin-bottom:18px}.faq-item{border:1px solid var(--line);border-radius:14px;background:#fff;margin:12px 0;overflow:hidden}.faq-item summary{cursor:pointer;list-style:none;padding:18px 20px;font-weight:900;color:var(--dark);display:flex;justify-content:space-between;gap:20px}.faq-item summary::after{content:"+";color:var(--accent);font-weight:900}.faq-item[open] summary::after{content:"-"}.faq-answer{padding:0 20px 20px;color:var(--ink)}
    .cta-card{margin:46px 0 10px;padding:32px;border-radius:18px;background:var(--dark);color:#fff;text-align:center}.cta-card h2{border:0;margin:0 0 12px;padding:0;color:#fff}.cta-card p{color:#e8eef0}.cta-buttons{display:flex;flex-wrap:wrap;justify-content:center;gap:10px;margin-top:22px}.cta-buttons a{display:inline-flex;align-items:center;justify-content:center;padding:13px 16px;border-radius:10px;text-decoration:none;font-weight:900;color:#fff}.cta-buttons a:first-child{background:linear-gradient(135deg,var(--primary),var(--accent))}.cta-buttons a:not(:first-child){background:rgba(255,255,255,.12);border:1px solid rgba(255,255,255,.22)}
    .reference-guide{max-width:1100px;margin:48px auto 0;padding:36px 24px 56px;border-top:8px solid var(--accent);background:#fff}.reference-guide h2{border:0;margin:0 0 12px;padding:0;font-size:2rem}.reference-guide h3{margin:28px 0 10px;color:var(--dark);font-size:1.2rem}.reference-kicker{color:var(--accent);font-size:.82rem;font-weight:950;letter-spacing:.1em;text-transform:uppercase}.note-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;margin:22px 0}.note-card{border:1px solid var(--line);border-radius:14px;padding:18px;background:#fbfbfa}.note-card strong{display:block;color:var(--dark);margin-bottom:6px}.checklist{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px 18px;margin-top:12px}.checklist li{margin:0;padding-left:28px}.checklist li::before{content:"✓";color:var(--accent)}.spec-table{width:100%;border-collapse:collapse;margin:16px 0 0;font-size:.95rem}.spec-table th,.spec-table td{text-align:left;border-bottom:1px solid var(--line);padding:10px 8px;vertical-align:top}.spec-table th{color:var(--dark);font-weight:900;background:#fbfbfa}
    footer{padding:32px;text-align:center;background:#f6f7f7;color:#687477}@media(max-width:1040px){.nav-links{gap:.85rem}.nav-links a{font-size:.82rem}.cta-button{padding:10px 12px}}@media(max-width:850px){.nav-links{display:none}.nav-inner{padding:.9rem 1rem}.blog-master-header{padding:52px 18px}.content{padding:36px 18px}.hero-image{margin:-18px 14px 0;width:calc(100% - 28px)}.stat-grid,.note-grid,.checklist{grid-template-columns:1fr}.cta-card{padding:26px 18px}.note-dot{width:20px;height:20px}.note-dot::after{left:auto;right:-6px;transform:translateY(6px)}.note-dot:hover::after,.note-dot:focus-visible::after{transform:translateY(0)}}
  </style>
</head>
<body>
  <nav class="bloomie-master-nav" aria-label="Bloomie Staffing"><div class="nav-inner"><a href="/" class="logo">Bloomie <span>Staffing</span></a><button class="note-dot" aria-label="Reference note: master navigation" data-note="Use the master Bloomie nav/app nav. Sarah should not recreate custom navigation per post. Mobile must collapse instead of wrapping or overlapping.">?</button><ul class="nav-links"><li><a href="/#roles">Meet the Team</a></li><li><a href="/#live-demo">Testimonials</a></li><li><a href="/ai-employee-vs-chatbot">AI vs Chatbots</a></li><li><a href="/ai-employee-for-financial-advisors">Financial Advisors</a></li><li><a href="/ai-employee-for-real-estate-agents">Real Estate</a></li><li><a href="/p/blog">Blog</a></li><li><a href="/p/faq">FAQ</a></li><li><a href="/pricing">Pricing</a></li><li><a class="cta-button" href="/book-demo">Book a Demo</a></li></ul></div></nav>
  <a class="blog-back-link" href="/p/blog">&larr; Back to Blog</a>
  <header class="blog-master-header"><h1>Doing Your Own Marketing <button class="note-dot" aria-label="Reference note: title and subtitle" data-note="Title must be big, specific, and question/problem-led. Subtitle explains the practical promise without sounding like a landing page.">?</button></h1><p>A field-note playbook for advisors who need a weekly marketing rhythm without turning business development into a second job.</p></header>
  <img class="hero-image" src="https://njfhzabmaxhfzekbzpzz.supabase.co/storage/v1/object/public/bloom-images/blog/blog-doing-your-own-marketing/hero-generated-2026-06-25.png" alt="Advisor marketing workflow with laptop, notebook, and weekly planning materials">
  <section class="podcast-player" aria-label="Podcast companion"><div class="podcast-top"><div><p class="podcast-label">Podcast companion</p><h2>Listen first: the simple version <button class="note-dot" aria-label="Reference note: podcast block" data-note="Podcast block belongs under the hero before the author row. Use real bloom-audio when available; placeholder only for internal visual testing.">?</button></h2><p>A quick plain-language listen for advisors who want a steadier marketing rhythm without carrying every follow-up task in memory.</p></div><span class="podcast-status">Marcus Chen · 8:02</span></div><div class="audio-placeholder">Audio placeholder: use real public bloom-audio URL when available</div></section>
  <main class="content">
    <div class="author-row"><div class="author-avatar-ring"><img src="https://njfhzabmaxhfzekbzpzz.supabase.co/storage/v1/object/public/bloom-images/blog/blog-doing-your-own-marketing/author-marcus.png" alt="Marcus Chen"></div><div><div class="author-name">Marcus Chen <button class="note-dot" aria-label="Reference note: author row" data-note="Author image is circular with a Bloomie gradient ring, different from the hero image, followed by author/company/date metadata.">?</button></div><div>Bloomie Staffing contributor focused on AI employee workflows for financial advisors · July 2, 2026</div></div></div>
    <blockquote>We asked what happens when financial advisors handle marketing themselves. The answer was not “post more.” The answer was a weekly operating cadence that keeps referrals, content, events, email, and follow-up moving without stealing the advisor from client work.</blockquote>
    <p>Advisor marketing works when it answers the questions prospects are already taking to Google, Reddit, client forums, and AI search: how to find better leads, how to build a book without inherited clients, how fast follow-up should happen, how onboarding gets delayed, and whether advisor fees are worth it. The post has to solve one of those problems with enough evidence that a skeptical advisor trusts the advice.</p>
    <p>That means a Bloomie blog cannot be a polished guess. It needs a researched point of view, source-backed facts, and a practical workflow the reader could use this week. The advisors who stay visible are usually not doing flashier marketing. They have a rhythm that keeps the pipeline, referral conversations, and follow-up from living only in their head.</p>
    <p>The goal is not to turn an advisor into a full-time marketer. The goal is to make marketing operational enough that the advisor can keep showing up with useful ideas while someone, or something, keeps the moving pieces organized.</p>
    <section class="stat-grid" aria-label="Research-backed advisor marketing facts"><div class="stat-card"><span class="stat-number">$3,119</span><p>Kitces research found this average cost to acquire a financial-advisor client, including advisor time. <button class="note-dot" aria-label="Reference note: visible stats" data-note="Visible stats build trust. Name the source in the card, but save clickable links for body text so readers do not click away too early.">?</button></p></div><div class="stat-card"><span class="stat-number">85%</span><p>Broadridge reported that advisors find it challenging to make time for marketing.</p></div><div class="stat-card"><span class="stat-number">56%</span><p>Fidelity notes existing-client referrals are the main source of qualified leads filling a firm's pipeline.</p></div></section>
    <h2>The pattern was not lack of ideas</h2>
    <p>Most advisors already know what their clients ask about. They hear questions about retirement timing, inheritance, taxes, family transitions, market volatility, business exits, and whether the next generation will keep the relationship. That is more than enough raw material for useful content.</p>
    <p>The issue is that those ideas arrive in the middle of meetings, phone calls, review prep, and service work. Without a system, they become scattered notes instead of a dependable marketing engine.</p>
    <div class="highlight"><strong>Field note:</strong> Marketing is not one task. It is a pipeline habit that needs an owner every week.</div>
    <h2>The research says time is the expensive part</h2>
    <p>Advisor marketing breaks down because the expensive resource is often the advisor's own time. <a class="source-link" href="https://www.kitces.com/blog/client-acquisition-cost-financial-advisor-marketing-efficiency-lifetime-client-value-lead-generation-satisfaction/" target="_blank" rel="noopener">Kitces research</a> found the average total client acquisition cost for a financial advisor was $3,119, and $2,600 of that was advisor time rather than hard-dollar marketing spend.</p>
    <p><a class="source-link" href="https://info.advisorstream.com/financial-advisor-marketing-trends-report-2024" target="_blank" rel="noopener">Broadridge's 2024 Financial Advisor Marketing Trends Report</a> points to the same operational pressure from another angle: 80% of advisors handle their own marketing, 85% say finding time for marketing is challenging, and advisors average only 2.1 hours per week on marketing activity.</p>
    <p>That is why the solution is not "try harder." The solution is a weekly operating system that protects advisor judgment for the places it matters and delegates the research, drafting, reminders, CRM cleanup, and reporting that make consistency possible.</p>
    <div class="highlight"><strong>Trust rule:</strong> Every Bloomie blog should name the problem advisors already search for, support the answer with credible evidence, and turn the research into a practical next step.</div>
    <h2>Example: when a paid lead is worth it <button class="note-dot" aria-label="Reference note: practical example" data-note="Every authority post needs at least one concrete scenario: paid-lead math, missed follow-up, onboarding delay, CRM cleanup, or book-building rhythm.">?</button></h2>
    <p>Imagine an advisor pays $150 for a lead. The answer is not automatically yes or no. The lead becomes worth pursuing only if the household fits the advisor's minimum relationship profile, has a real planning need, gets contacted quickly, receives a clear recap, and is placed into a nurture sequence if they are not ready for a second meeting.</p>
    <p>Without that system, the advisor is paying for names and hoping memory does the rest. With that system, the advisor can measure cost per real conversation, cost per second meeting, eventual AUM potential, and which source produces clients instead of noise. That is the difference between "paid leads are bad" and "paid leads need an operating system."</p>
    <div class="highlight"><strong>Example standard:</strong> A Bloomie blog should include at least one practical scenario like this so the reader can see the advice working in a real advisor workflow.</div>
    <h2>A weekly rhythm makes marketing smaller</h2>
    <p>A practical advisor marketing week can be simple. Monday is pipeline review. Tuesday is one useful authority idea. Wednesday is referral follow-up. Thursday is event or nurture follow-up. Friday is measurement and cleanup. None of those jobs need to take over the day, but each one needs to happen before the week disappears.</p>
    <p>This matters because advisory growth is rarely one big campaign. It is a chain of small, visible moments: the prospect who saw a clear answer, the client who remembered a friend, the attorney who received a useful follow-up, the seminar attendee who got a thoughtful second message.</p>
    <ul><li>New prospects added by source</li><li>Referral asks sent with context</li><li>Follow-up notes captured after events</li><li>One useful content topic published or drafted</li><li>Next-step reminders created before the week ends</li></ul>
    <h2>Where a Bloomie helps</h2>
    <p>A Bloomie should not replace advisor judgment. It should keep the recurring work from slipping. That means preparing draft ideas from real client questions, summarizing pipeline movement, creating referral reminders, cleaning CRM notes, drafting event follow-up, and preparing a weekly report that shows what marketing activity created real conversations.</p>
    <p>The advisor still reviews the message, owns the relationship, and decides what is appropriate. The Bloomie handles the repeatable work that makes consistency possible.</p>
    <h2>Monday is for pipeline reality</h2>
    <p>The week should start with a plain view of who is already in motion. Which introductions came in last week? Which seminar attendees asked a second question? Which client mentioned a friend, a parent, a business sale, or a child who needs guidance? This is where many advisors lose momentum because the useful signals are scattered across email, meeting notes, texts, and memory.</p>
    <p>A Bloomie can turn that scattered activity into a short Monday pipeline brief. The brief does not need to be fancy. It should tell the advisor who needs attention, why the person matters, what the last interaction was, and what the next useful move could be. That one page makes the rest of the marketing week less reactive.</p>
    <div class="highlight"><strong>Advisor rule:</strong> If the pipeline is not reviewed every week, marketing becomes guessing. The first job is knowing who is already warm.</div>
    <h2>Tuesday is for one useful idea</h2>
    <p>One useful idea is enough when it is specific. Advisors do not need to publish a giant essay every week. They need to answer the question that clients and prospects are already asking. A post about what to bring to a first meeting, how to think about fees, how to prepare for retirement income, or how families can organize inherited accounts can do more than a generic reminder to schedule a review.</p>
    <p>The best content sounds like it came from the advisor's real conversations. It names the moment the reader recognizes and gives them a next step. A Bloomie can collect those recurring questions, draft the first version, prepare a short email version, and turn the same idea into a few follow-up prompts for referral partners or prospects.</p>
    <h2>Wednesday is for referrals with context</h2>
    <p>Referral marketing often fails because the ask is too vague. "Keep me in mind" is easy to ignore. A better referral rhythm is specific: who the advisor helps, what transition or problem is relevant, and what makes the introduction timely. That could mean business owners preparing for a sale, widows who need help organizing accounts, families receiving an inheritance, or high-earning professionals trying to turn income into long-term security.</p>
    <p>The data supports giving referrals real operational attention. <a class="source-link" href="https://clearingcustody.fidelity.com/insights/spotlights/growth-hub/prospect" target="_blank" rel="noopener">Fidelity says referrals from existing clients</a> are the main source of qualified leads filling a firm's pipeline today, and <a class="source-link" href="https://smartasset.com/advisor-resources/best-referral-sources-for-financial-advisors-2023" target="_blank" rel="noopener">SmartAsset's coverage of a 2024 Broadridge survey</a> reported that 46% of advisors named referrals and word of mouth as a top marketing channel.</p>
    <p>A Bloomie can help by turning client and partner conversations into specific referral reminders. It can draft a note that says, in plain language, what kind of person the advisor is trying to help this month. The advisor still decides who should receive it. The system simply prevents the referral habit from disappearing when the week gets full.</p>
    <h2>Thursday is for nurture and event follow-up</h2>
    <p>Many advisors do the hard part of marketing and then lose the easy part. They host the webinar, attend the event, speak on a panel, meet the center of influence, or have the first call. Then the follow-up is delayed because client work takes priority. By the time the advisor returns to the list, the conversation feels colder than it needed to be.</p>
    <p>Thursday should be the day that warm conversations get organized. A Bloomie can summarize who attended, what they asked, what they clicked, what they downloaded, and what message should go next. That does not mean every person gets a sales pitch. It means the right person gets the right next step while the conversation still has energy.</p>
    <h2>Friday is for measurement, not vanity</h2>
    <p>The end of the week should answer a simple question: what created real conversations? Not just impressions, clicks, or opens, but actual movement. Did a referral ask produce an introduction? Did a client education email get replies? Did a seminar follow-up create second meetings? Did the content topic show up later in a prospect conversation?</p>
    <p>This is where a Bloomie can make marketing feel less emotional. Instead of guessing whether marketing is working, the advisor gets a weekly report with source, activity, response, and next step. Over time, that report shows which topics, partners, and follow-up patterns are worth repeating.</p>
    <div class="highlight"><strong>The practical difference:</strong> The advisor should not have to remember every marketing thread. The system should carry the threads back to the advisor when a decision or personal touch is needed.</div>
    <section class="faq-accordion"><h2>Questions Advisors Ask <button class="note-dot" aria-label="Reference note: Q&A accordion" data-note="Accordion Q&A is for GEO and reader usefulness. Each answer starts direct, then gives a workflow, stat, source-backed fact, or example. No vague filler.">?</button></h2><details class="faq-item"><summary>What should financial advisors do each week to market consistently?</summary><div class="faq-answer"><p>Financial advisors should run a five-part weekly rhythm: Monday pipeline review, Tuesday one client-question article or email, Wednesday specific referral follow-up, Thursday nurture or event follow-up, and Friday measurement. This protects advisor time, which Kitces research found was $2,600 of the average $3,119 client acquisition cost.</p></div></details><details class="faq-item"><summary>Can an AI employee help without replacing relationship work?</summary><div class="faq-answer"><p>Yes. A Bloomie can own repeatable marketing operations such as source research, content drafts, referral reminders, CRM cleanup, event follow-up, and Friday reporting. The advisor still approves messaging, handles compliance judgment, and keeps the client relationship.</p></div></details><details class="faq-item"><summary>Where should an advisor start if marketing feels scattered?</summary><div class="faq-answer"><p>Start with warm relationships and source tracking. Fidelity notes existing-client referrals are a major source of qualified leads, and Broadridge-related reporting shows referrals and word of mouth remain a top advisor marketing channel, so the first system should capture referral context, next steps, and follow-up timing.</p></div></details></section>
    <section class="cta-card"><h2>Ready to make advisor marketing feel staffed? <button class="note-dot" aria-label="Reference note: CTA" data-note="CTA stays near the bottom after the helpful body. No external links here. Use the exact three Bloomie buttons.">?</button></h2><p>Bloomie Staffing helps financial advisors hire reliable AI employees for pipeline tracking, content drafts, referral reminders, CRM cleanup, email nurture, event follow-up, and weekly marketing reports.</p><div class="cta-buttons"><a href="tel:+18005551234">Call Us Now</a><a href="/book-demo">Schedule a Demo</a><a href="/book-demo">Interview an AI Employee</a></div></section>
  </main>
  <footer>© 2026 Bloomie Staffing. All rights reserved.</footer>
  <section class="reference-guide" aria-label="Reference-only production notes">
    <p class="reference-kicker">Reference-only notes for Sarah</p>
    <h2>Bloomie Blog Master Checklist</h2>
    <p>This section is for the internal master PDF only. Do not publish these notes on the live blog post. Use them as the final inspection list before any scheduled blog is marked complete.</p>
    <div class="note-grid">
      <div class="note-card"><strong>Audience problem first</strong>Open with the exact advisor question people are already asking Google, Reddit, forums, sales calls, or AI search. Example: "Should I buy leads?" then answer yes/no/it depends with reasons.</div>
      <div class="note-card"><strong>Research plus field experience</strong>Use Bloomie's own workflow observations, but back the core recommendation with credible sources such as Kitces, Broadridge, Fidelity, Schwab, Cerulli, McKinsey, Deloitte, InvestmentNews, Financial Planning, ThinkAdvisor, WealthManagement.com, or Forbes Advisor.</div>
      <div class="note-card"><strong>Stats must be visible</strong>Include at least 2 concrete stats, benchmark numbers, or source-backed facts in the article body. Stats should help the reader trust the advice, not decorate the page.</div>
      <div class="note-card"><strong>Examples make it useful</strong>Include at least 1 practical scenario: paid-lead math, missed follow-up, onboarding delay, CRM cleanup, book-building rhythm, or client review prep.</div>
    </div>
    <h3>Visual and CSS Standards</h3>
    <table class="spec-table">
      <tr><th>Element</th><th>Required Standard</th></tr>
      <tr><td>Master nav</td><td>Use the standard Bloomie nav/app nav. Do not invent new nav variants. On mobile, hide the crowded link row instead of wrapping or overlapping it.</td></tr>
      <tr><td>Header</td><td>Full-width Bloomie gradient, centered white H1, subtitle below. H1 uses clamp around 2.55rem to 3.55rem, line-height 1.05, font-weight 900.</td></tr>
      <tr><td>Hero image</td><td>Public Supabase image URL, 16:9 aspect ratio, max-width about 980px, rounded 18px, overlaps the colored header.</td></tr>
      <tr><td>Podcast block</td><td>Appears under hero before author row. Use real public bloom-audio URL when available; placeholder is acceptable only for internal tests.</td></tr>
      <tr><td>Author row</td><td>Circular author avatar with Bloomie gradient ring, author name, company/role, and publication date.</td></tr>
      <tr><td>Article body</td><td>820px content width, 16px base text, line-height 1.7, short paragraphs, orange/pink section accents, peach highlight boxes, triangle bullets.</td></tr>
      <tr><td>Q&A</td><td>Accordion style, 2-3 questions, direct answer first, concrete example/stat/source-backed fact second. Do not use vague answers.</td></tr>
      <tr><td>CTA</td><td>Dark slate CTA near the bottom, after the useful body and Q&A/source material. Buttons: Call Us Now, Schedule a Demo, Interview an AI Employee.</td></tr>
    </table>
    <h3>Final Pre-Publish Checklist</h3>
    <ul class="checklist">
      <li>Topic answers a real advisor question, not a generic content idea.</li>
      <li>Intro answers the core question in the first 40-50 words.</li>
      <li>Long authority posts are allowed when the topic needs depth; avoid thin posts.</li>
      <li>At least 2 credible sources were checked and used.</li>
      <li>At least 2 stats/facts are visible in the article body.</li>
      <li>At least 1 practical example shows the workflow in action.</li>
      <li>Use 2-4 subtle inline source links where facts are explained; avoid external links in the hero, intro CTA, final CTA, or button areas.</li>
      <li>Hero and author images are public URLs and loaded in browser verification.</li>
      <li>Back to Blog link, master nav, author/date, podcast block, Q&A, CTA, and footer are present.</li>
      <li>Live /p URL opens, /p/blog index updates, image paths are not broken, and the page passes visual inspection.</li>
    </ul>
  </section>
</body>
</html>
"""

OUT.write_text(html)
print(OUT)
